using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "d603235ef0d1ad0c")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BrandImage1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Brand Image 1 Text
		///</summary>
		[ImplementPropertyType("brandImage1Text")]
		public string BrandImage1Text
		{
			get { return this.GetPropertyValue<string>("brandImage1Text"); }
		}

		///<summary>
		/// BrandImage2
		///</summary>
		[ImplementPropertyType("brandImage2")]
		public object BrandImage2
		{
			get { return this.GetPropertyValue("brandImage2"); }
		}

		///<summary>
		/// Brand Image 2 Link
		///</summary>
		[ImplementPropertyType("brandImage2Link")]
		public string BrandImage2Link
		{
			get { return this.GetPropertyValue<string>("brandImage2Link"); }
		}

		///<summary>
		/// Brand Image 2 Link Text
		///</summary>
		[ImplementPropertyType("brandImage2LinkText")]
		public string BrandImage2LinkText
		{
			get { return this.GetPropertyValue<string>("brandImage2LinkText"); }
		}

		///<summary>
		/// Brand Image 2 Text
		///</summary>
		[ImplementPropertyType("brandImage2Text")]
		public string BrandImage2Text
		{
			get { return this.GetPropertyValue<string>("brandImage2Text"); }
		}

		///<summary>
		/// Brand Image 3 Link 1
		///</summary>
		[ImplementPropertyType("brandImage3Link1")]
		public string BrandImage3Link1
		{
			get { return this.GetPropertyValue<string>("brandImage3Link1"); }
		}

		///<summary>
		/// Brand Image 3 Link 2
		///</summary>
		[ImplementPropertyType("brandImage3Link2")]
		public string BrandImage3Link2
		{
			get { return this.GetPropertyValue<string>("brandImage3Link2"); }
		}

		///<summary>
		/// Brand Image 3 Link 3
		///</summary>
		[ImplementPropertyType("brandImage3Link3")]
		public string BrandImage3Link3
		{
			get { return this.GetPropertyValue<string>("brandImage3Link3"); }
		}

		///<summary>
		/// Brand Image 3 Link 4
		///</summary>
		[ImplementPropertyType("brandImage3Link4")]
		public string BrandImage3Link4
		{
			get { return this.GetPropertyValue<string>("brandImage3Link4"); }
		}

		///<summary>
		/// brandTile1
		///</summary>
		[ImplementPropertyType("brandTile1")]
		public object BrandTile1
		{
			get { return this.GetPropertyValue("brandTile1"); }
		}

		///<summary>
		/// BrandTile2
		///</summary>
		[ImplementPropertyType("brandTile2")]
		public IEnumerable<IPublishedContent> BrandTile2
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("brandTile2"); }
		}

		///<summary>
		/// BrandTile3
		///</summary>
		[ImplementPropertyType("brandTile3")]
		public IEnumerable<IPublishedContent> BrandTile3
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("brandTile3"); }
		}

		///<summary>
		/// BrandTile4
		///</summary>
		[ImplementPropertyType("brandTile4")]
		public IEnumerable<IPublishedContent> BrandTile4
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("brandTile4"); }
		}

		///<summary>
		/// BrandTile5
		///</summary>
		[ImplementPropertyType("brandTile5")]
		public IEnumerable<IPublishedContent> BrandTile5
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("brandTile5"); }
		}

		///<summary>
		/// BrandTile6
		///</summary>
		[ImplementPropertyType("brandTile6")]
		public IEnumerable<IPublishedContent> BrandTile6
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("brandTile6"); }
		}

		///<summary>
		/// BrandTile7
		///</summary>
		[ImplementPropertyType("brandTile7")]
		public IEnumerable<IPublishedContent> BrandTile7
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("brandTile7"); }
		}

		///<summary>
		/// BrandTile8
		///</summary>
		[ImplementPropertyType("brandTile8")]
		public IEnumerable<IPublishedContent> BrandTile8
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("brandTile8"); }
		}

		///<summary>
		/// Language
		///</summary>
		[ImplementPropertyType("chooseFlag")]
		public string ChooseFlag
		{
			get { return this.GetPropertyValue<string>("chooseFlag"); }
		}

		///<summary>
		/// eventDescription1
		///</summary>
		[ImplementPropertyType("eventDescription1")]
		public string EventDescription1
		{
			get { return this.GetPropertyValue<string>("eventDescription1"); }
		}

		///<summary>
		/// eventDescription2
		///</summary>
		[ImplementPropertyType("eventDescription2")]
		public string EventDescription2
		{
			get { return this.GetPropertyValue<string>("eventDescription2"); }
		}

		///<summary>
		/// EventTile1Title1
		///</summary>
		[ImplementPropertyType("eventTile1Title1")]
		public string EventTile1Title1
		{
			get { return this.GetPropertyValue<string>("eventTile1Title1"); }
		}

		///<summary>
		/// EventTile1Title2
		///</summary>
		[ImplementPropertyType("eventTile1Title2")]
		public string EventTile1Title2
		{
			get { return this.GetPropertyValue<string>("eventTile1Title2"); }
		}

		///<summary>
		/// Event Tile Image
		///</summary>
		[ImplementPropertyType("eventTileImage")]
		public IEnumerable<IPublishedContent> EventTileImage
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("eventTileImage"); }
		}

		///<summary>
		/// Facebook Link
		///</summary>
		[ImplementPropertyType("facebookLink")]
		public string FacebookLink
		{
			get { return this.GetPropertyValue<string>("facebookLink"); }
		}

		///<summary>
		/// Footer Section 1 Title
		///</summary>
		[ImplementPropertyType("footerSection1Title")]
		public string FooterSection1Title
		{
			get { return this.GetPropertyValue<string>("footerSection1Title"); }
		}

		///<summary>
		/// Footer Section 2 Title
		///</summary>
		[ImplementPropertyType("footerSection2Title")]
		public string FooterSection2Title
		{
			get { return this.GetPropertyValue<string>("footerSection2Title"); }
		}

		///<summary>
		/// Footer Section 3 Title
		///</summary>
		[ImplementPropertyType("footerSection3Title")]
		public string FooterSection3Title
		{
			get { return this.GetPropertyValue<string>("footerSection3Title"); }
		}

		///<summary>
		/// Footer Section 4 Title
		///</summary>
		[ImplementPropertyType("footerSection4Title")]
		public string FooterSection4Title
		{
			get { return this.GetPropertyValue<string>("footerSection4Title"); }
		}

		///<summary>
		/// Latitude
		///</summary>
		[ImplementPropertyType("latitude")]
		public int Latitude
		{
			get { return this.GetPropertyValue<int>("latitude"); }
		}

		///<summary>
		/// Longitude
		///</summary>
		[ImplementPropertyType("longitude")]
		public int Longitude
		{
			get { return this.GetPropertyValue<int>("longitude"); }
		}

		///<summary>
		/// MainNavigation
		///</summary>
		[ImplementPropertyType("mainNavigation")]
		public Umbraco.Web.Models.RelatedLinks MainNavigation
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("mainNavigation"); }
		}

		///<summary>
		/// Movie Description 1
		///</summary>
		[ImplementPropertyType("movieDescription1")]
		public string MovieDescription1
		{
			get { return this.GetPropertyValue<string>("movieDescription1"); }
		}

		///<summary>
		/// Movie Description 2
		///</summary>
		[ImplementPropertyType("movieDescription2")]
		public string MovieDescription2
		{
			get { return this.GetPropertyValue<string>("movieDescription2"); }
		}

		///<summary>
		/// Page Copy Rights
		///</summary>
		[ImplementPropertyType("pageCopyRights")]
		public string PageCopyRights
		{
			get { return this.GetPropertyValue<string>("pageCopyRights"); }
		}

		///<summary>
		/// Section 1 Content 1
		///</summary>
		[ImplementPropertyType("section1Content1")]
		public string Section1Content1
		{
			get { return this.GetPropertyValue<string>("section1Content1"); }
		}

		///<summary>
		/// Section 1 Content 2
		///</summary>
		[ImplementPropertyType("section1Content2")]
		public string Section1Content2
		{
			get { return this.GetPropertyValue<string>("section1Content2"); }
		}

		///<summary>
		/// Section 1 Content 3
		///</summary>
		[ImplementPropertyType("section1Content3")]
		public string Section1Content3
		{
			get { return this.GetPropertyValue<string>("section1Content3"); }
		}

		///<summary>
		/// Section 1 Content 4
		///</summary>
		[ImplementPropertyType("section1Content4")]
		public string Section1Content4
		{
			get { return this.GetPropertyValue<string>("section1Content4"); }
		}

		///<summary>
		/// Section 1 Content 5
		///</summary>
		[ImplementPropertyType("section1Content5")]
		public string Section1Content5
		{
			get { return this.GetPropertyValue<string>("section1Content5"); }
		}

		///<summary>
		/// Section 1 Subtile 2
		///</summary>
		[ImplementPropertyType("section1Subtile2")]
		public string Section1Subtile2
		{
			get { return this.GetPropertyValue<string>("section1Subtile2"); }
		}

		///<summary>
		/// Section 1 Subtitle 1
		///</summary>
		[ImplementPropertyType("section1Subtitle1")]
		public string Section1Subtitle1
		{
			get { return this.GetPropertyValue<string>("section1Subtitle1"); }
		}

		///<summary>
		/// Section 1 Subtitle 3
		///</summary>
		[ImplementPropertyType("section1Subtitle3")]
		public string Section1Subtitle3
		{
			get { return this.GetPropertyValue<string>("section1Subtitle3"); }
		}

		///<summary>
		/// Section 1 Subtitle 4
		///</summary>
		[ImplementPropertyType("section1Subtitle4")]
		public string Section1Subtitle4
		{
			get { return this.GetPropertyValue<string>("section1Subtitle4"); }
		}

		///<summary>
		/// Section 1 Subtitle 5
		///</summary>
		[ImplementPropertyType("section1Subtitle5")]
		public string Section1Subtitle5
		{
			get { return this.GetPropertyValue<string>("section1Subtitle5"); }
		}

		///<summary>
		/// Section 2 Content Links
		///</summary>
		[ImplementPropertyType("section2ContentLinks")]
		public Umbraco.Web.Models.RelatedLinks Section2ContentLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("section2ContentLinks"); }
		}

		///<summary>
		/// Section 3 Content 1
		///</summary>
		[ImplementPropertyType("section3Content1")]
		public string Section3Content1
		{
			get { return this.GetPropertyValue<string>("section3Content1"); }
		}

		///<summary>
		/// Section 3 Content 2
		///</summary>
		[ImplementPropertyType("section3Content2")]
		public string Section3Content2
		{
			get { return this.GetPropertyValue<string>("section3Content2"); }
		}

		///<summary>
		/// Section 3 Subtitle 1
		///</summary>
		[ImplementPropertyType("section3Subtitle1")]
		public string Section3Subtitle1
		{
			get { return this.GetPropertyValue<string>("section3Subtitle1"); }
		}

		///<summary>
		/// Section 3 Subtitle 2
		///</summary>
		[ImplementPropertyType("section3Subtitle2")]
		public string Section3Subtitle2
		{
			get { return this.GetPropertyValue<string>("section3Subtitle2"); }
		}

		///<summary>
		/// Slider
		///</summary>
		[ImplementPropertyType("slider")]
		public Newtonsoft.Json.Linq.JToken Slider
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("slider"); }
		}

		///<summary>
		/// social media facebook link
		///</summary>
		[ImplementPropertyType("socialMediaFacebookLink")]
		public string SocialMediaFacebookLink
		{
			get { return this.GetPropertyValue<string>("socialMediaFacebookLink"); }
		}

		///<summary>
		/// social media instagram link
		///</summary>
		[ImplementPropertyType("socialMediaInstagramLink")]
		public string SocialMediaInstagramLink
		{
			get { return this.GetPropertyValue<string>("socialMediaInstagramLink"); }
		}

		///<summary>
		/// social media linkdin link
		///</summary>
		[ImplementPropertyType("socialMediaLinkdinLink")]
		public string SocialMediaLinkdinLink
		{
			get { return this.GetPropertyValue<string>("socialMediaLinkdinLink"); }
		}

		///<summary>
		/// social media twitter link
		///</summary>
		[ImplementPropertyType("socialMediaTwitterLink")]
		public string SocialMediaTwitterLink
		{
			get { return this.GetPropertyValue<string>("socialMediaTwitterLink"); }
		}

		///<summary>
		/// Twitter Link
		///</summary>
		[ImplementPropertyType("twitterLink")]
		public string TwitterLink
		{
			get { return this.GetPropertyValue<string>("twitterLink"); }
		}

		///<summary>
		/// Youtube Tile 1 Thumbnail
		///</summary>
		[ImplementPropertyType("youtubeTile1Thumbnail")]
		public object YoutubeTile1Thumbnail
		{
			get { return this.GetPropertyValue("youtubeTile1Thumbnail"); }
		}

		///<summary>
		/// Youtube Tile 2 Thumbnail
		///</summary>
		[ImplementPropertyType("youtubeTile2Thumbnail")]
		public object YoutubeTile2Thumbnail
		{
			get { return this.GetPropertyValue("youtubeTile2Thumbnail"); }
		}

		///<summary>
		/// YoutubeVideoTile1
		///</summary>
		[ImplementPropertyType("youtubeVideoTile1")]
		public Newtonsoft.Json.Linq.JToken YoutubeVideoTile1
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("youtubeVideoTile1"); }
		}

		///<summary>
		/// YoutubeVideoTile2
		///</summary>
		[ImplementPropertyType("youtubeVideoTile2")]
		public Newtonsoft.Json.Linq.JToken YoutubeVideoTile2
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("youtubeVideoTile2"); }
		}
	}

	/// <summary>Dine</summary>
	[PublishedContentModel("dine")]
	public partial class Dine : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dine";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Dine(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Dine, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BrandImage1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// BrandImage1Text
		///</summary>
		[ImplementPropertyType("brandImage1Text")]
		public string BrandImage1Text
		{
			get { return this.GetPropertyValue<string>("brandImage1Text"); }
		}

		///<summary>
		/// BrandImage2
		///</summary>
		[ImplementPropertyType("brandImage2")]
		public object BrandImage2
		{
			get { return this.GetPropertyValue("brandImage2"); }
		}

		///<summary>
		/// BrandImage3
		///</summary>
		[ImplementPropertyType("brandImage3")]
		public object BrandImage3
		{
			get { return this.GetPropertyValue("brandImage3"); }
		}

		///<summary>
		/// BrandImage4
		///</summary>
		[ImplementPropertyType("brandImage4")]
		public object BrandImage4
		{
			get { return this.GetPropertyValue("brandImage4"); }
		}

		///<summary>
		/// BrandImage5
		///</summary>
		[ImplementPropertyType("brandImage5")]
		public object BrandImage5
		{
			get { return this.GetPropertyValue("brandImage5"); }
		}

		///<summary>
		/// BrandLogoIcons
		///</summary>
		[ImplementPropertyType("brandLogoIcons")]
		public object BrandLogoIcons
		{
			get { return this.GetPropertyValue("brandLogoIcons"); }
		}

		///<summary>
		/// Description1
		///</summary>
		[ImplementPropertyType("description1")]
		public string Description1
		{
			get { return this.GetPropertyValue<string>("description1"); }
		}

		///<summary>
		/// Description2
		///</summary>
		[ImplementPropertyType("description2")]
		public string Description2
		{
			get { return this.GetPropertyValue<string>("description2"); }
		}

		///<summary>
		/// Description3
		///</summary>
		[ImplementPropertyType("description3")]
		public string Description3
		{
			get { return this.GetPropertyValue<string>("description3"); }
		}

		///<summary>
		/// Description4
		///</summary>
		[ImplementPropertyType("description4")]
		public string Description4
		{
			get { return this.GetPropertyValue<string>("description4"); }
		}

		///<summary>
		/// Description5
		///</summary>
		[ImplementPropertyType("description5")]
		public string Description5
		{
			get { return this.GetPropertyValue<string>("description5"); }
		}

		///<summary>
		/// DescriptionTitle1
		///</summary>
		[ImplementPropertyType("descriptionTitle1")]
		public string DescriptionTitle1
		{
			get { return this.GetPropertyValue<string>("descriptionTitle1"); }
		}

		///<summary>
		/// DescriptionTitle2
		///</summary>
		[ImplementPropertyType("descriptionTitle2")]
		public string DescriptionTitle2
		{
			get { return this.GetPropertyValue<string>("descriptionTitle2"); }
		}

		///<summary>
		/// DescriptionTitle3
		///</summary>
		[ImplementPropertyType("descriptionTitle3")]
		public string DescriptionTitle3
		{
			get { return this.GetPropertyValue<string>("descriptionTitle3"); }
		}

		///<summary>
		/// DescriptionTitle4
		///</summary>
		[ImplementPropertyType("descriptionTitle4")]
		public string DescriptionTitle4
		{
			get { return this.GetPropertyValue<string>("descriptionTitle4"); }
		}

		///<summary>
		/// DescriptionTitle5
		///</summary>
		[ImplementPropertyType("descriptionTitle5")]
		public string DescriptionTitle5
		{
			get { return this.GetPropertyValue<string>("descriptionTitle5"); }
		}

		///<summary>
		/// DescriptionTitle6
		///</summary>
		[ImplementPropertyType("descriptionTitle6")]
		public string DescriptionTitle6
		{
			get { return this.GetPropertyValue<string>("descriptionTitle6"); }
		}

		///<summary>
		/// Shop Logo
		///</summary>
		[ImplementPropertyType("shopLogo")]
		public object ShopLogo
		{
			get { return this.GetPropertyValue("shopLogo"); }
		}

		///<summary>
		/// title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Entertain</summary>
	[PublishedContentModel("entertain")]
	public partial class Entertain : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "entertain";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Entertain(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Entertain, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brand Image 1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Brand Image 2
		///</summary>
		[ImplementPropertyType("brandImage2")]
		public object BrandImage2
		{
			get { return this.GetPropertyValue("brandImage2"); }
		}

		///<summary>
		/// Brand Image 2 Description
		///</summary>
		[ImplementPropertyType("brandImage2Description")]
		public string BrandImage2Description
		{
			get { return this.GetPropertyValue<string>("brandImage2Description"); }
		}

		///<summary>
		/// Brand Image 3
		///</summary>
		[ImplementPropertyType("brandImage3")]
		public object BrandImage3
		{
			get { return this.GetPropertyValue("brandImage3"); }
		}

		///<summary>
		/// BrandImage3 Description
		///</summary>
		[ImplementPropertyType("brandImage3Description")]
		public string BrandImage3Description
		{
			get { return this.GetPropertyValue<string>("brandImage3Description"); }
		}

		///<summary>
		/// Brand Image 4
		///</summary>
		[ImplementPropertyType("brandImage4")]
		public object BrandImage4
		{
			get { return this.GetPropertyValue("brandImage4"); }
		}

		///<summary>
		/// BrandImage4 Description
		///</summary>
		[ImplementPropertyType("brandImage4Description")]
		public string BrandImage4Description
		{
			get { return this.GetPropertyValue<string>("brandImage4Description"); }
		}

		///<summary>
		/// Brand Image 5
		///</summary>
		[ImplementPropertyType("brandImage5")]
		public object BrandImage5
		{
			get { return this.GetPropertyValue("brandImage5"); }
		}

		///<summary>
		/// BrandImage5 Description
		///</summary>
		[ImplementPropertyType("brandImage5Description")]
		public string BrandImage5Description
		{
			get { return this.GetPropertyValue<string>("brandImage5Description"); }
		}

		///<summary>
		/// Brand Image 6
		///</summary>
		[ImplementPropertyType("brandImage6")]
		public object BrandImage6
		{
			get { return this.GetPropertyValue("brandImage6"); }
		}

		///<summary>
		/// BrandImage6 Description
		///</summary>
		[ImplementPropertyType("brandImage6Description")]
		public string BrandImage6Description
		{
			get { return this.GetPropertyValue<string>("brandImage6Description"); }
		}

		///<summary>
		/// Brand Image 7
		///</summary>
		[ImplementPropertyType("brandImage7")]
		public object BrandImage7
		{
			get { return this.GetPropertyValue("brandImage7"); }
		}

		///<summary>
		/// BrandImage7 Description
		///</summary>
		[ImplementPropertyType("brandImage7Description")]
		public string BrandImage7Description
		{
			get { return this.GetPropertyValue<string>("brandImage7Description"); }
		}

		///<summary>
		/// Description 1
		///</summary>
		[ImplementPropertyType("description1")]
		public string Description1
		{
			get { return this.GetPropertyValue<string>("description1"); }
		}

		///<summary>
		/// Description 2
		///</summary>
		[ImplementPropertyType("description2")]
		public string Description2
		{
			get { return this.GetPropertyValue<string>("description2"); }
		}

		///<summary>
		/// Lg Movie Image
		///</summary>
		[ImplementPropertyType("lgMovieImage")]
		public object LgMovieImage
		{
			get { return this.GetPropertyValue("lgMovieImage"); }
		}

		///<summary>
		/// MovieSlider
		///</summary>
		[ImplementPropertyType("movieSlider")]
		public Newtonsoft.Json.Linq.JToken MovieSlider
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("movieSlider"); }
		}

		///<summary>
		/// Now Showing Slider
		///</summary>
		[ImplementPropertyType("nowShowingSlider")]
		public object NowShowingSlider
		{
			get { return this.GetPropertyValue("nowShowingSlider"); }
		}
	}

	/// <summary>More</summary>
	[PublishedContentModel("more")]
	public partial class More : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "more";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public More(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<More, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Tourist</summary>
	[PublishedContentModel("tourist")]
	public partial class Tourist : More
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tourist";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Tourist(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Tourist, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brand Image 1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Brand Image 2
		///</summary>
		[ImplementPropertyType("brandImage2")]
		public object BrandImage2
		{
			get { return this.GetPropertyValue("brandImage2"); }
		}

		///<summary>
		/// Brand Image 3
		///</summary>
		[ImplementPropertyType("brandImage3")]
		public object BrandImage3
		{
			get { return this.GetPropertyValue("brandImage3"); }
		}

		///<summary>
		/// Brand Image 4
		///</summary>
		[ImplementPropertyType("brandImage4")]
		public object BrandImage4
		{
			get { return this.GetPropertyValue("brandImage4"); }
		}

		///<summary>
		/// Description 1
		///</summary>
		[ImplementPropertyType("description1")]
		public string Description1
		{
			get { return this.GetPropertyValue<string>("description1"); }
		}

		///<summary>
		/// Description 1 Title
		///</summary>
		[ImplementPropertyType("description1Title")]
		public string Description1Title
		{
			get { return this.GetPropertyValue<string>("description1Title"); }
		}

		///<summary>
		/// Description 2
		///</summary>
		[ImplementPropertyType("description2")]
		public string Description2
		{
			get { return this.GetPropertyValue<string>("description2"); }
		}

		///<summary>
		/// Description 2 Title
		///</summary>
		[ImplementPropertyType("description2Title")]
		public string Description2Title
		{
			get { return this.GetPropertyValue<string>("description2Title"); }
		}

		///<summary>
		/// Description 3
		///</summary>
		[ImplementPropertyType("description3")]
		public string Description3
		{
			get { return this.GetPropertyValue<string>("description3"); }
		}

		///<summary>
		/// Description 3 Title
		///</summary>
		[ImplementPropertyType("description3Title")]
		public string Description3Title
		{
			get { return this.GetPropertyValue<string>("description3Title"); }
		}

		///<summary>
		/// Description 4
		///</summary>
		[ImplementPropertyType("description4")]
		public string Description4
		{
			get { return this.GetPropertyValue<string>("description4"); }
		}

		///<summary>
		/// Description 4 Title
		///</summary>
		[ImplementPropertyType("description4Title")]
		public string Description4Title
		{
			get { return this.GetPropertyValue<string>("description4Title"); }
		}
	}

	/// <summary>OFFERS</summary>
	[PublishedContentModel("shop")]
	public partial class Shop : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "shop";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Shop(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Shop, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// AddOffers
		///</summary>
		[ImplementPropertyType("addOffers")]
		public object AddOffers
		{
			get { return this.GetPropertyValue("addOffers"); }
		}

		///<summary>
		/// Brand Image 1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// BrandTitle
		///</summary>
		[ImplementPropertyType("brandTitle")]
		public string BrandTitle
		{
			get { return this.GetPropertyValue<string>("brandTitle"); }
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("category")]
		public IEnumerable<string> Category
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("category"); }
		}

		///<summary>
		/// Links
		///</summary>
		[ImplementPropertyType("links")]
		public Umbraco.Web.Models.RelatedLinks Links
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("links"); }
		}
	}

	/// <summary>ContactUs</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : More
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brand Image 1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Description 1
		///</summary>
		[ImplementPropertyType("description1")]
		public IHtmlString Description1
		{
			get { return this.GetPropertyValue<IHtmlString>("description1"); }
		}

		///<summary>
		/// Description 1 Title
		///</summary>
		[ImplementPropertyType("description1Title")]
		public string Description1Title
		{
			get { return this.GetPropertyValue<string>("description1Title"); }
		}

		///<summary>
		/// Facebook Url
		///</summary>
		[ImplementPropertyType("facebookUrl")]
		public string FacebookUrl
		{
			get { return this.GetPropertyValue<string>("facebookUrl"); }
		}

		///<summary>
		/// Twitter Url
		///</summary>
		[ImplementPropertyType("twitterUrl")]
		public string TwitterUrl
		{
			get { return this.GetPropertyValue<string>("twitterUrl"); }
		}
	}

	/// <summary>AboutUs</summary>
	[PublishedContentModel("aboutUs")]
	public partial class AboutUs : More
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Add Customer Services
		///</summary>
		[ImplementPropertyType("addCustomerServices")]
		public object AddCustomerServices
		{
			get { return this.GetPropertyValue("addCustomerServices"); }
		}

		///<summary>
		/// Add Manar Mall Policies
		///</summary>
		[ImplementPropertyType("addManarMallPolicies")]
		public object AddManarMallPolicies
		{
			get { return this.GetPropertyValue("addManarMallPolicies"); }
		}

		///<summary>
		/// AlHamra
		///</summary>
		[ImplementPropertyType("alHamra")]
		public IHtmlString AlHamra
		{
			get { return this.GetPropertyValue<IHtmlString>("alHamra"); }
		}

		///<summary>
		/// Bike Parking
		///</summary>
		[ImplementPropertyType("bikeParking")]
		public string BikeParking
		{
			get { return this.GetPropertyValue<string>("bikeParking"); }
		}

		///<summary>
		/// Brand Image 1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Car Parking Link
		///</summary>
		[ImplementPropertyType("carParkingLink")]
		public string CarParkingLink
		{
			get { return this.GetPropertyValue<string>("carParkingLink"); }
		}

		///<summary>
		/// ManarMall
		///</summary>
		[ImplementPropertyType("manarMall")]
		public IHtmlString ManarMall
		{
			get { return this.GetPropertyValue<IHtmlString>("manarMall"); }
		}

		///<summary>
		/// Parking Description
		///</summary>
		[ImplementPropertyType("parkingDescription")]
		public string ParkingDescription
		{
			get { return this.GetPropertyValue<string>("parkingDescription"); }
		}

		///<summary>
		/// Special Parking
		///</summary>
		[ImplementPropertyType("specialParking")]
		public string SpecialParking
		{
			get { return this.GetPropertyValue<string>("specialParking"); }
		}

		///<summary>
		/// TextSlider
		///</summary>
		[ImplementPropertyType("textSlider")]
		public Newtonsoft.Json.Linq.JToken TextSlider
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("textSlider"); }
		}

		///<summary>
		/// Time Schedule
		///</summary>
		[ImplementPropertyType("timeSchedule")]
		public object TimeSchedule
		{
			get { return this.GetPropertyValue("timeSchedule"); }
		}
	}

	/// <summary>Search Results</summary>
	[PublishedContentModel("searchResults")]
	public partial class SearchResults : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "searchResults";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SearchResults(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SearchResults, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BodyText
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("bodyText"); }
		}
	}

	/// <summary>Events</summary>
	[PublishedContentModel("events")]
	public partial class Events : More
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "events";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Events(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Events, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// addEvents
		///</summary>
		[ImplementPropertyType("addEvents")]
		public Newtonsoft.Json.Linq.JToken AddEvents
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("addEvents"); }
		}

		///<summary>
		/// brandImage1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}
	}

	/// <summary>Shop</summary>
	[PublishedContentModel("shopping")]
	public partial class Shopping : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "shopping";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Shopping(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Shopping, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// brandImage1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// brandImage11
		///</summary>
		[ImplementPropertyType("brandImage11")]
		public object BrandImage11
		{
			get { return this.GetPropertyValue("brandImage11"); }
		}

		///<summary>
		/// brandImage12
		///</summary>
		[ImplementPropertyType("brandImage12")]
		public object BrandImage12
		{
			get { return this.GetPropertyValue("brandImage12"); }
		}

		///<summary>
		/// brandImage13
		///</summary>
		[ImplementPropertyType("brandImage13")]
		public object BrandImage13
		{
			get { return this.GetPropertyValue("brandImage13"); }
		}

		///<summary>
		/// brandImage10
		///</summary>
		[ImplementPropertyType("brandImage14")]
		public object BrandImage14
		{
			get { return this.GetPropertyValue("brandImage14"); }
		}

		///<summary>
		/// brandImage2
		///</summary>
		[ImplementPropertyType("brandImage2")]
		public object BrandImage2
		{
			get { return this.GetPropertyValue("brandImage2"); }
		}

		///<summary>
		/// brandImage2Text
		///</summary>
		[ImplementPropertyType("brandImage2Text")]
		public IHtmlString BrandImage2Text
		{
			get { return this.GetPropertyValue<IHtmlString>("brandImage2Text"); }
		}

		///<summary>
		/// brandImage3
		///</summary>
		[ImplementPropertyType("brandImage3")]
		public object BrandImage3
		{
			get { return this.GetPropertyValue("brandImage3"); }
		}

		///<summary>
		/// brandImage6
		///</summary>
		[ImplementPropertyType("brandImage4")]
		public object BrandImage4
		{
			get { return this.GetPropertyValue("brandImage4"); }
		}

		///<summary>
		/// brandImage7
		///</summary>
		[ImplementPropertyType("brandImage5")]
		public object BrandImage5
		{
			get { return this.GetPropertyValue("brandImage5"); }
		}

		///<summary>
		/// brandImage4
		///</summary>
		[ImplementPropertyType("brandImage6")]
		public object BrandImage6
		{
			get { return this.GetPropertyValue("brandImage6"); }
		}

		///<summary>
		/// brandImage8
		///</summary>
		[ImplementPropertyType("brandImage7")]
		public object BrandImage7
		{
			get { return this.GetPropertyValue("brandImage7"); }
		}

		///<summary>
		/// brandImage9
		///</summary>
		[ImplementPropertyType("brandImage8")]
		public object BrandImage8
		{
			get { return this.GetPropertyValue("brandImage8"); }
		}

		///<summary>
		/// brandImage5
		///</summary>
		[ImplementPropertyType("brandImage9")]
		public object BrandImage9
		{
			get { return this.GetPropertyValue("brandImage9"); }
		}
	}

	/// <summary>ShopDetails</summary>
	[PublishedContentModel("shopDetails")]
	public partial class ShopDetails : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "shopDetails";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ShopDetails(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ShopDetails, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About Shop
		///</summary>
		[ImplementPropertyType("aboutShop")]
		public IHtmlString AboutShop
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutShop"); }
		}

		///<summary>
		/// brandBackgroundColor
		///</summary>
		[ImplementPropertyType("brandBackgroundColor")]
		public object BrandBackgroundColor
		{
			get { return this.GetPropertyValue("brandBackgroundColor"); }
		}

		///<summary>
		/// brandImage1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Facebook Url
		///</summary>
		[ImplementPropertyType("facebookUrl")]
		public string FacebookUrl
		{
			get { return this.GetPropertyValue<string>("facebookUrl"); }
		}

		///<summary>
		/// Shop Contact
		///</summary>
		[ImplementPropertyType("shopContact")]
		public IHtmlString ShopContact
		{
			get { return this.GetPropertyValue<IHtmlString>("shopContact"); }
		}

		///<summary>
		/// shopImages
		///</summary>
		[ImplementPropertyType("shopImages")]
		public object ShopImages
		{
			get { return this.GetPropertyValue("shopImages"); }
		}

		///<summary>
		/// shopImages2
		///</summary>
		[ImplementPropertyType("shopImages2")]
		public object ShopImages2
		{
			get { return this.GetPropertyValue("shopImages2"); }
		}

		///<summary>
		/// Shop Location
		///</summary>
		[ImplementPropertyType("shopLocation")]
		public IHtmlString ShopLocation
		{
			get { return this.GetPropertyValue<IHtmlString>("shopLocation"); }
		}

		///<summary>
		/// Shop Name
		///</summary>
		[ImplementPropertyType("shopName")]
		public string ShopName
		{
			get { return this.GetPropertyValue<string>("shopName"); }
		}

		///<summary>
		/// shopTimings
		///</summary>
		[ImplementPropertyType("shopTimings")]
		public IEnumerable<string> ShopTimings
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("shopTimings"); }
		}

		///<summary>
		/// Shop Title
		///</summary>
		[ImplementPropertyType("shopTitle")]
		public string ShopTitle
		{
			get { return this.GetPropertyValue<string>("shopTitle"); }
		}

		///<summary>
		/// slider1
		///</summary>
		[ImplementPropertyType("slider1")]
		public object Slider1
		{
			get { return this.GetPropertyValue("slider1"); }
		}

		///<summary>
		/// slider2
		///</summary>
		[ImplementPropertyType("slider2")]
		public object Slider2
		{
			get { return this.GetPropertyValue("slider2"); }
		}

		///<summary>
		/// Twitter Url
		///</summary>
		[ImplementPropertyType("twitterUrl")]
		public string TwitterUrl
		{
			get { return this.GetPropertyValue<string>("twitterUrl"); }
		}
	}

	/// <summary>Shops</summary>
	[PublishedContentModel("shops")]
	public partial class Shops : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "shops";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Shops(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Shops, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brand Image 1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Shop Tiles
		///</summary>
		[ImplementPropertyType("shopTiles")]
		public Newtonsoft.Json.Linq.JToken ShopTiles
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("shopTiles"); }
		}
	}

	/// <summary>Gifts</summary>
	[PublishedContentModel("gifts")]
	public partial class Gifts : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "gifts";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Gifts(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Gifts, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brand Image 1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// Description Title
		///</summary>
		[ImplementPropertyType("descriptionTitle")]
		public IHtmlString DescriptionTitle
		{
			get { return this.GetPropertyValue<IHtmlString>("descriptionTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Voucher Image
		///</summary>
		[ImplementPropertyType("voucherImage")]
		public object VoucherImage
		{
			get { return this.GetPropertyValue("voucherImage"); }
		}
	}

	/// <summary>Promotions</summary>
	[PublishedContentModel("promotions")]
	public partial class Promotions : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "promotions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Promotions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Promotions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Brand Image 1
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public object BrandImage1
		{
			get { return this.GetPropertyValue("brandImage1"); }
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("category")]
		public Umbraco.Web.Models.RelatedLinks Category
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("category"); }
		}

		///<summary>
		/// Description 1
		///</summary>
		[ImplementPropertyType("description1")]
		public IHtmlString Description1
		{
			get { return this.GetPropertyValue<IHtmlString>("description1"); }
		}

		///<summary>
		/// Description 1 Title
		///</summary>
		[ImplementPropertyType("description1Title")]
		public IHtmlString Description1Title
		{
			get { return this.GetPropertyValue<IHtmlString>("description1Title"); }
		}

		///<summary>
		/// Description 2
		///</summary>
		[ImplementPropertyType("description2")]
		public IHtmlString Description2
		{
			get { return this.GetPropertyValue<IHtmlString>("description2"); }
		}

		///<summary>
		/// Description 2 Title
		///</summary>
		[ImplementPropertyType("description2Title")]
		public string Description2Title
		{
			get { return this.GetPropertyValue<string>("description2Title"); }
		}

		///<summary>
		/// List Name
		///</summary>
		[ImplementPropertyType("listName")]
		public string ListName
		{
			get { return this.GetPropertyValue<string>("listName"); }
		}

		///<summary>
		/// Loyalty Image
		///</summary>
		[ImplementPropertyType("loyaltyImage")]
		public object LoyaltyImage
		{
			get { return this.GetPropertyValue("loyaltyImage"); }
		}

		///<summary>
		/// Partners
		///</summary>
		[ImplementPropertyType("partners")]
		public Umbraco.Web.Models.RelatedLinks Partners
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("partners"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Store Locator</summary>
	[PublishedContentModel("storeLocator")]
	public partial class StoreLocator : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "storeLocator";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StoreLocator(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StoreLocator, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link 1
		///</summary>
		[ImplementPropertyType("link1")]
		public Newtonsoft.Json.Linq.JToken Link1
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("link1"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
